version: '3'

services:
  api:
    build: .
    ports:
      - 4000:4000
    command: npm start
    container_name: tackleAI
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  